// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcQ-Bm7Cfw8TFUePvYCcOlVjHoTz21ME',
    appId: '1:62996163666:web:baf391fef780aa57d8838b',
    messagingSenderId: '62996163666',
    projectId: 'freemium-novel-app',
    authDomain: 'freemium-novel-app.firebaseapp.com',
    storageBucket: 'freemium-novel-app.firebasestorage.app',
    measurementId: 'G-20MDS57WMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhu6ppCneGC_cBnp0q5nvznktKu9DBE9o',
    appId: '1:62996163666:android:c9ee63a70d7e6595d8838b',
    messagingSenderId: '62996163666',
    projectId: 'freemium-novel-app',
    storageBucket: 'freemium-novel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfva8YpcMHEJfDJzZ6nCcEVpT353SWvxo',
    appId: '1:62996163666:ios:263dd014941f830ed8838b',
    messagingSenderId: '62996163666',
    projectId: 'freemium-novel-app',
    storageBucket: 'freemium-novel-app.firebasestorage.app',
    iosClientId: '62996163666-fvat4vdpmeadgldvg8jo1skm6p6ugckr.apps.googleusercontent.com',
    iosBundleId: 'com.example.freemiumNovelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfva8YpcMHEJfDJzZ6nCcEVpT353SWvxo',
    appId: '1:62996163666:ios:263dd014941f830ed8838b',
    messagingSenderId: '62996163666',
    projectId: 'freemium-novel-app',
    storageBucket: 'freemium-novel-app.firebasestorage.app',
    iosClientId: '62996163666-fvat4vdpmeadgldvg8jo1skm6p6ugckr.apps.googleusercontent.com',
    iosBundleId: 'com.example.freemiumNovelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCcQ-Bm7Cfw8TFUePvYCcOlVjHoTz21ME',
    appId: '1:62996163666:web:b38b759ebb960314d8838b',
    messagingSenderId: '62996163666',
    projectId: 'freemium-novel-app',
    authDomain: 'freemium-novel-app.firebaseapp.com',
    storageBucket: 'freemium-novel-app.firebasestorage.app',
    measurementId: 'G-KFBVQFC4P7',
  );
}
